name:                HaskellTreeDSL
version:             0.1.0.0
github:              mark1010/HaskellTreeDSL
license:             BSD-3-Clause
author:              "MarkH"
maintainer:          "10847477+mark1010@users.noreply.github.com"
copyright:           "2023 MarkH"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mark1010/HaskellTreeDSL>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- megaparsec
- parser-combinators
- text
- raw-strings-qq
- ansi-terminal

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  HaskellTreeDSL-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellTreeDSL

tests:
  HaskellTreeDSL-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-unused-imports
    - -Wno-unused-top-binds

    dependencies:
    - HaskellTreeDSL
    - hspec
    - hspec-megaparsec
